version: '3.6'

services:
  master-diet-app:
    container_name: master-diet-backend-application
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data/master-diet-app-data
    ports:
      - "8081:8081"