spring:
  main:
    lazy-initialization: true
  data:
    jpa:
      repositories:
        bootstrap-mode: lazy
  config:
    location: classpath:/application.properties
  datasource:
    url: jdbc:postgresql://master-diet-db:5432/master-diet-db
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        use_jdbc_metadata_defaults: false

  security:
    oauth2:
      client:
        registration:
          google:
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          facebook:
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - public_profile
          github:
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - user:email
              - read:user
server:
  port: 8081